### ISSUE TITLE
Add Mobile Dev Icons

### ISSUE THREAD

**Issue by aking618** [MikeCodesDotNET/ColoredBadges#23] opened 2020-07-16 06:26 UTC
Do you think you could add Icons for Android Studio, Flutter, and Dart

**Comment by klaasnicolaas** [comment] 2020-07-16 12:42
I can make the Android Studio version 😉

**Comment by klaasnicolaas** [comment] 2020-07-17 00:10
Btw this PR is a duplicate of #20 😉

**Comment by aking618** [comment] 2020-07-17 00:11
Sorry about that 👌

**Comment by klaasnicolaas** [comment] 2020-07-17 10:22
#31 Will add the two badges 😉

**Closed** 2020-07-17 10:59 UTC
